#!/usr/bin/env python3
"""
enrich.py — all-in-one people enrichment.

For each person in a CSV, ask Claude (with the web-search tool) to find, and
VERIFY, four things — filling only the cells that are still blank:

  - Current Affiliation          where they work / what they do now
  - Company (if any) // status   ONLY if they FOUNDED a company: "<url> // <year>"
  - LinkedIn                     canonical https://www.linkedin.com/in/<slug>/
  - Personal website             their own site/blog/portfolio (not a company/social page)

plus three confidence columns + a one-line evidence note, so you can triage the
uncertain rows. It is conservative by design: same-name people are the main risk,
so it abstains (leaves a cell blank) when it can't confirm the right person.

The headline accuracy trick — LINK-BACK VERIFICATION: once a LinkedIn URL is
found, a candidate personal site that links *back* to that exact profile is
near-certainly theirs. That check is deterministic (run locally, here in Python),
so those hits are marked `linkback` and can be trusted blindly.

This is the standalone, re-runnable version of the pipeline. (The CSVs shipped
with this repo were generated by the Claude Code workflow in ./workflows, which
fans the same prompt out across many agents in parallel; this script is the
single-process equivalent you can run yourself with one API key.)

SETUP
  pip install -r requirements.txt
  export ANTHROPIC_API_KEY=sk-ant-...
  # point it at your sheet and run:
  INPUT_CSV="people.csv" CONTEXT_SUFFIX="Y Combinator" python3 enrich.py

Resumable: results are written row-by-row and people already in OUTPUT_CSV are
skipped, so a stopped run (quota, network, Ctrl-C) picks up where it left off.
"""

import csv, json, os, re, sys, time
import anthropic
import requests

# ----------------------------- CONFIG --------------------------------------
# Per the Anthropic SDK guidance the default is the most capable model. For a
# bulk run over hundreds of people, ANTHROPIC_MODEL=claude-haiku-4-5 is far
# cheaper and works well for this search-and-extract task.
MODEL          = os.environ.get("ANTHROPIC_MODEL", "claude-opus-4-8")

INPUT_CSV      = os.environ.get("INPUT_CSV", "people.csv")
OUTPUT_CSV     = os.environ.get("OUTPUT_CSV", "people_enriched.csv")

NAME_COLUMN    = "Name"                # column holding the person's name
CONTEXT_COLUMN = "Past Affiliation"    # optional hint column (role/tenure); "" to skip
# Network context that pins the right person, e.g. "Y Combinator" or "Square / Block".
CONTEXT_SUFFIX = os.environ.get("CONTEXT_SUFFIX", "")

MAX_TOKENS     = 8000
MAX_RETRIES    = 4
PAUSE_SECONDS  = 0.3
LINKBACK_TIMEOUT = 12

# Anthropic server-side web tools (latest versions; dynamic filtering is automatic).
WEB_TOOLS = [
    {"type": "web_search_20260209", "name": "web_search"},
    {"type": "web_fetch_20260209",  "name": "web_fetch"},
]

NEW_COLS = ["Current Affiliation", "Company (if any) // status", "LinkedIn", "Personal website",
            "linkedin_conf", "website_conf", "founded_conf", "enrich_evidence"]

# ----------------------------- PROMPT --------------------------------------
PROMPT = """You are enriching ONE person. Use the web_search / web_fetch tools to find VERIFIED facts. Be precise and CONSERVATIVE — same-name people are the main risk; abstain (return "" with confidence "none"/"low") when you cannot confirm THIS specific person.

PERSON:
  name: {name}
  context / role / tenure: {role}
  network: {suffix}

Use the role/tenure and network to disambiguate from other people with the same name.

FIND (only what you can confirm for THIS person):
1. linkedin — their linkedin.com/in/ profile. Confirm it's this person (matches the network, role, timeline, field). Return canonical https://www.linkedin.com/in/<slug>/ , or "" if unsure.
2. current_affiliation — where they work now / what they do now (company + role). "" if unknown.
3. founded_company — did THIS person FOUND or CO-FOUND a company? Founding only, not merely employed. If yes: "<company homepage url> // <year founded>" (use "// ?" if the year is unconfirmed; the company name instead of a URL if it's defunct / has no live site). "" otherwise.
4. personal_website — their OWN site/blog/portfolio. NOT a company marketing site, a social profile, a wiki/news/aggregator page, or a same-name person's site. "" if none.

Search efficiently. Then output ONLY a JSON object (no other text) in this exact shape:
{{"linkedin":"","linkedin_confidence":"high|medium|low|none","current_affiliation":"","founded_company":"","founded_confidence":"high|medium|low|none","personal_website":"","website_confidence":"high|medium|low|none","evidence":"1-2 sentences: how you confirmed identity, key sources, any same-name flag"}}"""

# ----------------------------- HELPERS -------------------------------------
def li_slug(url):
    m = re.search(r"linkedin\.com/in/([^/?#\s\"']+)", url or "", re.I)
    return m.group(1).lower().rstrip("/") if m else ""

HREFS = re.compile(r'href=["\']([^"\']+)["\']', re.I)

def links_back(website, linkedin):
    """Deterministic check: does the personal site link to the exact LinkedIn profile?"""
    slug = li_slug(linkedin)
    if not slug or not website:
        return False
    try:
        r = requests.get(website, timeout=LINKBACK_TIMEOUT,
                         headers={"User-Agent": "Mozilla/5.0 (compatible; enrichment-script)"})
        if r.status_code != 200 or not r.text:
            return False
        return any(li_slug(h) == slug for h in HREFS.findall(r.text))
    except Exception:
        return False

def parse_json(text):
    t = re.sub(r"^```(?:json)?|```$", "", (text or "").strip(), flags=re.M).strip()
    s, e = t.find("{"), t.rfind("}")
    if s == -1 or e == -1:
        return {}
    try:
        return json.loads(t[s:e + 1])
    except Exception:
        return {}

def norm_founded(val):
    v = (val or "").strip()
    if not v:
        return ""
    m = re.match(r"^(https?://\S+)\s*//\s*$", v)   # "url // " -> "url // ?"
    return f"{m.group(1)} // ?" if m else ("" if v.startswith("//") else v)

def call_claude(client, prompt):
    """One enrichment call. Handles the web-search server loop (pause_turn) and retries."""
    messages = [{"role": "user", "content": prompt}]
    last = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            for _ in range(6):  # server-tool continuation loop
                resp = client.messages.create(
                    model=MODEL, max_tokens=MAX_TOKENS,
                    thinking={"type": "adaptive"},
                    tools=WEB_TOOLS,
                    messages=messages,
                )
                if resp.stop_reason == "pause_turn":
                    messages.append({"role": "assistant", "content": resp.content})
                    continue
                break
            text = "".join(b.text for b in resp.content if b.type == "text")
            return parse_json(text)
        except (anthropic.RateLimitError, anthropic.APIStatusError, anthropic.APIConnectionError) as e:
            last = e
            time.sleep(attempt * 3)
    print(f"   call failed after {MAX_RETRIES} tries: {last}")
    return {}

def already_done(path):
    done = set()
    if os.path.exists(path):
        with open(path, newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                done.add(row.get(NAME_COLUMN, ""))
    return done

# ----------------------------- MAIN ----------------------------------------
def main():
    if not os.environ.get("ANTHROPIC_API_KEY"):
        sys.exit("Set ANTHROPIC_API_KEY first (export ANTHROPIC_API_KEY=sk-ant-...).")
    if not os.path.exists(INPUT_CSV):
        sys.exit(f"Input file not found: {INPUT_CSV}")

    with open(INPUT_CSV, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        sys.exit("Input CSV is empty.")

    client = anthropic.Anthropic()
    done = already_done(OUTPUT_CSV)
    write_header = not os.path.exists(OUTPUT_CSV)
    base_cols = [c for c in rows[0].keys() if c not in NEW_COLS]
    fieldnames = base_cols + NEW_COLS

    found = 0
    with open(OUTPUT_CSV, "a", newline="", encoding="utf-8") as out:
        writer = csv.DictWriter(out, fieldnames=fieldnames, extrasaction="ignore")
        if write_header:
            writer.writeheader()

        for i, row in enumerate(rows, 1):
            name = (row.get(NAME_COLUMN) or "").strip()
            if not name or name in done:
                continue
            role = (row.get(CONTEXT_COLUMN) or "").strip() if CONTEXT_COLUMN else ""
            for c in NEW_COLS:
                row.setdefault(c, "")

            res = call_claude(client, PROMPT.format(
                name=name, role=role or "(unknown)", suffix=CONTEXT_SUFFIX or "(none)"))

            li      = (res.get("linkedin") or "").strip()
            web     = (res.get("personal_website") or "").strip()
            li_conf = res.get("linkedin_confidence", "none")
            web_conf = res.get("website_confidence", "none")

            # deterministic link-back upgrade
            if web and li and links_back(web, li):
                web_conf = "linkback"

            def fill(col, val):
                if not row.get(col, "").strip() and val:
                    row[col] = val; return True
                return False

            n = 0
            n += fill("LinkedIn", li)
            ca = (res.get("current_affiliation") or "").strip()
            if (not row["Current Affiliation"].strip() or row["Current Affiliation"].strip().lower() == "unknown") and ca:
                row["Current Affiliation"] = ca; n += 1
            n += fill("Company (if any) // status", norm_founded(res.get("founded_company")))
            n += fill("Personal website", web)

            row["linkedin_conf"]   = li_conf
            row["website_conf"]    = web_conf
            row["founded_conf"]    = res.get("founded_confidence", "none")
            row["enrich_evidence"] = (res.get("evidence") or "")[:500]

            if n:
                found += 1
            print(f"[{i}/{len(rows)}] {name}  ->  LI={li_conf} web={web_conf} "
                  f"founded={'Y' if row['Company (if any) // status'].strip() else '-'}")
            writer.writerow(row)
            out.flush()
            time.sleep(PAUSE_SECONDS)

    print(f"\nDone. Enriched {found} people. Results in {OUTPUT_CSV}")

if __name__ == "__main__":
    main()
